version: '3.9'
services:
  note_app:
    image: loneexile/note_app:latest
    container_name: note_app
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - voidbox_network

networks:
  voidbox_network:
    external: true
